### ISSUE TITLE
Current release in not installable on windows

### ISSUE THREAD

**Issue by MasterLamp** [ecency/esteem-surfer#296]
Hi all,

thanks for the release of the updated version. But I am not able to install it on my Windows 10 machine.

![image](https://user-images.githubusercontent.com/11429699/96980167-9b621d00-151f-11eb-8edc-cebb0d79b2ed.png)

Can you tell me which library I miss?
Thank you in advance.

Best regards,

Master Lamps

**Comment by feruzm** [comment]
@MasterLamp Is your windows 32 bit or 64 bit? Because I think our latest build only supports 64bit windows

**Comment by MasterLamp** [comment]
> @MasterLamp Is your windows 32 bit or 64 bit? Because I think our latest build only supports 64bit windows

A 64bit machine made it do for me. Thank you.
